version: 2

sources:
  - name: invoices  
    tables:
      - name: invoice_raw
      - name: invoice_item__raw
        # ATTENTION: This test will fail as data is not updated, it is here for illustration purposes
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

        loaded_at_field: _synced